# Generated by Django 4.1.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('album_artist', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(validators=[music.models.validate_year])),
                ('genre', models.CharField(default='Unknown', max_length=100)),
                ('number_of_discs', models.IntegerField(default=1, validators=[music.models.validate_number_of_discs])),
                ('number_of_tracks', models.IntegerField(validators=[music.models.validate_number_of_tracks])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250)),
                ('compilation', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('empty', 'Unrated'), ('0', '☆☆☆☆☆'), ('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default='empty', max_length=7)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-album_title',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('track_number', models.IntegerField(validators=[music.models.validate_number_of_tracks])),
                ('length', models.CharField(blank=True, max_length=7)),
                ('track_rating', models.CharField(choices=[('empty', 'Unrated'), ('0', '☆☆☆☆☆'), ('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default='empty', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250)),
                ('from_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
